"use client";

import Link from "next/link";
import { FileTextIcon } from "@/components/Icons";
import { CartesianGrid, Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

const pipeline = [
  { stage: "Captured", leads: "1,248", rate: 82.5, change: "12.4%", drop: "217", dropRate: "17.5%", color: "#7a5af8" },
  { stage: "Valid", leads: "1,030", rate: 68.2, change: "8.2%", drop: "327", dropRate: "31.8%", color: "#2e90fa" },
  { stage: "Qualified", leads: "703", rate: 54.1, change: "5.7%", drop: "323", dropRate: "45.9%", color: "#12b5cb" },
  { stage: "For sale", leads: "380", rate: 31.6, change: "9.1%", drop: "260", dropRate: "68.4%", color: "#f79009" },
  { stage: "Sold", leads: "120", rate: null, change: "4.3%", drop: "—", dropRate: "", color: "#12b76a" },
];
const activity = [
  { day: "May 24", published: 0, unpublished: 0 }, { day: "May 25", published: 0, unpublished: 0 }, { day: "May 26", published: 4, unpublished: 0 }, { day: "May 27", published: 3, unpublished: 1 }, { day: "May 28", published: 1, unpublished: 0 }, { day: "May 29", published: 0, unpublished: 0 }, { day: "May 30", published: 0, unpublished: 0 }, { day: "May 31", published: 8, unpublished: 1 }, { day: "Jun 01", published: 4, unpublished: 2 }, { day: "Jun 02", published: 0, unpublished: 0 }, { day: "Jun 03", published: 0, unpublished: 0 }, { day: "Jun 04", published: 0, unpublished: 0 }, { day: "Jun 05", published: 0, unpublished: 0 }, { day: "Jun 06", published: 0, unpublished: 0 },
];
const brandRevenue = [
  { name: "Evergreen Residential", value: 6240, color: "#4f46e5" }, { name: "Aurora Living", value: 3420, color: "#2e90fa" }, { name: "Maple Heights", value: 1850, color: "#12b5cb" }, { name: "Pine Valley", value: 780, color: "#f79009" }, { name: "Other Brands", value: 250, color: "#fdb022" },
];
const buyerRevenue = [
  { name: "Home Builders", value: 4980, color: "#4f46e5" }, { name: "Real Estate Agents", value: 3260, color: "#2e90fa" }, { name: "Property Managers", value: 2140, color: "#12b5cb" }, { name: "Investors", value: 1410, color: "#f79009" }, { name: "Other Buyers", value: 750, color: "#fdb022" },
];

export function AnalyticsDashboard() {
  return <div className="grid auto-rows-fr gap-5 lg:grid-cols-2"><PipelineCard /><PublishCard /><RevenueCard title="Revenue by brand" rows={brandRevenue} footer="View all brands →" href="/dashboard" /><RevenueCard title="Revenue by buyer" rows={buyerRevenue} footer="View all buyers →" href="/buyers" /></div>;
}
function Card({ children, className = "" }: { children: React.ReactNode; className?: string }) { return <div className={`card flex h-full min-h-[430px] flex-col p-5 ${className}`}>{children}</div>; }
function PipelineCard() {
  return <Card><div className="mb-7"><h2 className="text-base font-semibold tracking-tight">Lead pipeline overview</h2></div><div className="grid grid-cols-[1.1fr_.55fr_1.25fr_.75fr_.8fr] border-b border-line-soft px-1 pb-2 text-[11px] font-semibold text-faint"><span>Stage</span><span>Leads</span><span>Conversion rate</span><span>Change</span><span>Drop-off</span></div><div className="flex-1">{pipeline.map((row) => <div key={row.stage} className="grid grid-cols-[1.1fr_.55fr_1.25fr_.75fr_.8fr] items-center border-b border-line-soft px-1 py-3 text-xs"><span className="flex items-center gap-2 font-medium"><i className="h-2.5 w-2.5 rounded-full" style={{ background: row.color }} />{row.stage}</span><span className="font-semibold tabular-nums">{row.leads}</span><span className="flex items-center gap-2 text-faint">{row.rate === null ? "—" : <><span className="w-9 tabular-nums">{row.rate}%</span><span className="h-2 w-20 overflow-hidden rounded-full bg-raised"><span className="block h-full rounded-full" style={{ width: `${row.rate}%`, background: row.color }} /></span></>}</span><span className="font-semibold text-ok">↑ {row.change}</span><span className={row.drop === "—" ? "text-faint" : "font-semibold text-bad"}>{row.drop} <span className="font-normal text-faint">{row.dropRate && `(${row.dropRate})`}</span></span></div>)}</div><div className="mt-4 flex items-center justify-between rounded-lg border border-line-soft bg-raised/40 px-3 py-3 text-xs"><span className="font-semibold">Overall conversion <span className="font-normal text-faint">(Captured → Sold)</span></span><strong className="text-lg">9.6%</strong></div></Card>;
}
function PublishCard() {
  return <Card><div className="mb-3 flex items-center justify-between"><h2 className="text-base font-semibold tracking-tight">Publish activity</h2><span className="rounded-lg border border-line px-3 py-2 text-xs font-medium text-dim">Last 14 days <span className="ml-2 text-faint">⌄</span></span></div><div className="mb-2 flex gap-5 text-xs text-dim"><span className="flex items-center gap-2"><i className="h-2.5 w-2.5 rounded-full bg-primary" />Published</span><span className="flex items-center gap-2"><i className="h-2.5 w-2.5 rounded-full bg-line" />Unpublished</span></div><div className="min-h-[220px] flex-1"><ResponsiveContainer width="100%" height="100%"><LineChart data={activity} margin={{ top: 12, right: 8, left: -22, bottom: 0 }}><CartesianGrid stroke="var(--line-soft)" strokeDasharray="2 3" vertical={false} /><XAxis dataKey="day" tick={{ fontSize: 10, fill: "var(--faint)" }} tickLine={false} axisLine={false} interval={2} /><YAxis domain={[0, 10]} ticks={[0, 2, 4, 6, 8, 10]} tick={{ fontSize: 10, fill: "var(--faint)" }} tickLine={false} axisLine={false} /><Tooltip contentStyle={{ borderRadius: 8, border: "1px solid var(--line)", fontSize: 12 }} /><Line type="monotone" dataKey="published" stroke="var(--primary)" strokeWidth={2.5} dot={{ r: 3, fill: "var(--primary)" }} activeDot={{ r: 5 }} /><Line type="monotone" dataKey="unpublished" stroke="var(--line)" strokeWidth={2} dot={{ r: 2, fill: "var(--line)" }} /></LineChart></ResponsiveContainer></div><div className="mt-3 grid grid-cols-2 divide-x divide-line rounded-lg border border-line-soft"><div className="flex items-center gap-3 px-3 py-3"><FileTextIcon size={20} className="text-primary" /><span><strong className="block text-lg leading-none">18</strong><small className="text-xs text-faint">Pages published</small></span></div><div className="flex items-center gap-3 px-3 py-3"><FileTextIcon size={20} className="text-dim" /><span><strong className="block text-lg leading-none">6</strong><small className="text-xs text-faint">Pages unpublished</small></span></div></div></Card>;
}
function RevenueCard({ title, rows, footer, href }: { title: string; rows: { name: string; value: number; color: string }[]; footer: string; href: string }) {
  return <Card className="pt-3"><div className="mb-0"><h2 className="text-base font-semibold tracking-tight">{title}</h2></div><div className="flex flex-1 items-center gap-3 max-sm:flex-col max-sm:justify-center"><div className="relative h-72 w-72 shrink-0"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={rows} dataKey="value" nameKey="name" innerRadius={92} outerRadius={140} paddingAngle={1} stroke="var(--surface)" strokeWidth={2}>{rows.map((row) => <Cell key={row.name} fill={row.color} />)}</Pie></PieChart></ResponsiveContainer><div className="absolute inset-0 grid place-content-center text-center"><strong className="text-xl tracking-tight">$12,540</strong><span className="mt-1 text-xs text-faint">Total revenue</span></div></div><div className="w-full min-w-0 space-y-2">{rows.map((row) => <div key={row.name} className="flex items-center gap-1.5 text-xs"><i className="h-2.5 w-2.5 shrink-0 rounded-full" style={{ background: row.color }} /><span className="min-w-0 flex-1 truncate font-medium">{row.name}</span><span className="tabular-nums">${row.value.toLocaleString()}</span><span className="w-10 text-right text-faint">{((row.value / 12540) * 100).toFixed(1)}%</span></div>)}</div></div><div className="mt-2 border-t border-line-soft pt-3 text-center text-sm font-semibold text-primary"><Link href={href}>{footer}</Link></div></Card>;
}
