// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/analytics" | "/brands/[id]" | "/brands/new" | "/buyers" | "/buyers/[id]" | "/dashboard" | "/deliver/[token]" | "/freshness" | "/home" | "/invite/[token]" | "/leads" | "/leads/[id]" | "/login" | "/packs/import" | "/portal/[token]" | "/search" | "/style" | "/team" | "/templates"
type AppRouteHandlerRoutes = "/api/assets/[id]" | "/api/brands/[id]/assets" | "/api/dev-e2e" | "/api/dev-seed-demo" | "/api/geo/parse" | "/api/geo/template" | "/api/leads" | "/api/leads/export.csv" | "/api/packs/import" | "/api/packs/template" | "/live/[brandSlug]/[[...path]]" | "/preview/[versionId]"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/analytics": {}
  "/api/assets/[id]": { "id": string; }
  "/api/brands/[id]/assets": { "id": string; }
  "/api/dev-e2e": {}
  "/api/dev-seed-demo": {}
  "/api/geo/parse": {}
  "/api/geo/template": {}
  "/api/leads": {}
  "/api/leads/export.csv": {}
  "/api/packs/import": {}
  "/api/packs/template": {}
  "/brands/[id]": { "id": string; }
  "/brands/new": {}
  "/buyers": {}
  "/buyers/[id]": { "id": string; }
  "/dashboard": {}
  "/deliver/[token]": { "token": string; }
  "/freshness": {}
  "/home": {}
  "/invite/[token]": { "token": string; }
  "/leads": {}
  "/leads/[id]": { "id": string; }
  "/live/[brandSlug]/[[...path]]": { "brandSlug": string; "path"?: string[]; }
  "/login": {}
  "/packs/import": {}
  "/portal/[token]": { "token": string; }
  "/preview/[versionId]": { "versionId": string; }
  "/search": {}
  "/style": {}
  "/team": {}
  "/templates": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
