// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analytics">> = Specific
  const handler = {} as typeof import("../../src/app/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/brands/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/brands/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/brands/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/brands/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/brands/new">> = Specific
  const handler = {} as typeof import("../../src/app/brands/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/buyers/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/buyers/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/buyers/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/buyers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/buyers">> = Specific
  const handler = {} as typeof import("../../src/app/buyers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/deliver/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/deliver/[token]">> = Specific
  const handler = {} as typeof import("../../src/app/deliver/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/freshness/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/freshness">> = Specific
  const handler = {} as typeof import("../../src/app/freshness/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/home/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/home">> = Specific
  const handler = {} as typeof import("../../src/app/home/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/invite/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invite/[token]">> = Specific
  const handler = {} as typeof import("../../src/app/invite/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/leads/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/leads/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/leads/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/leads/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/leads">> = Specific
  const handler = {} as typeof import("../../src/app/leads/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/packs/import/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/packs/import">> = Specific
  const handler = {} as typeof import("../../src/app/packs/import/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/portal/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portal/[token]">> = Specific
  const handler = {} as typeof import("../../src/app/portal/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/search/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/search">> = Specific
  const handler = {} as typeof import("../../src/app/search/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/style/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/style">> = Specific
  const handler = {} as typeof import("../../src/app/style/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/team/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/team">> = Specific
  const handler = {} as typeof import("../../src/app/team/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/templates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/templates">> = Specific
  const handler = {} as typeof import("../../src/app/templates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/assets/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/assets/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/assets/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/brands/[id]/assets/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/brands/[id]/assets">> = Specific
  const handler = {} as typeof import("../../src/app/api/brands/[id]/assets/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dev-e2e/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dev-e2e">> = Specific
  const handler = {} as typeof import("../../src/app/api/dev-e2e/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dev-seed-demo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dev-seed-demo">> = Specific
  const handler = {} as typeof import("../../src/app/api/dev-seed-demo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/geo/parse/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/geo/parse">> = Specific
  const handler = {} as typeof import("../../src/app/api/geo/parse/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/geo/template/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/geo/template">> = Specific
  const handler = {} as typeof import("../../src/app/api/geo/template/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/leads/export.csv/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leads/export.csv">> = Specific
  const handler = {} as typeof import("../../src/app/api/leads/export.csv/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/leads/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leads">> = Specific
  const handler = {} as typeof import("../../src/app/api/leads/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/packs/import/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/packs/import">> = Specific
  const handler = {} as typeof import("../../src/app/api/packs/import/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/packs/template/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/packs/template">> = Specific
  const handler = {} as typeof import("../../src/app/api/packs/template/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/live/[brandSlug]/[[...path]]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/live/[brandSlug]/[[...path]]">> = Specific
  const handler = {} as typeof import("../../src/app/live/[brandSlug]/[[...path]]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/preview/[versionId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/preview/[versionId]">> = Specific
  const handler = {} as typeof import("../../src/app/preview/[versionId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
